cc_binary(
    name = "serve",
    srcs = [
        "serve.c++",
    ],
    deps = [
        "//third_party/sandstorm:sandstorm",
    ],
    visibility = ["//visibility:public"],
    linkopts = [
        "-static",
    ],
)
